### ISSUE TITLE
Error HH411: missing dependency 

### ISSUE THREAD

**Issue by parseb** [St4rgarden/RiteOfMoloch#6]
Steps:
- `npm install`
- `nvm use --lts`  ( avoid Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported)
- `npx hardhat test`

Lead to:
```
Error HH411: The library @openzeppelin/contracts-upgradeable, imported from contracts/RiteOfMoloch.sol, is not installed. 
Try installing it using npm.
For more info go to https://hardhat.org/HH411 or run Hardhat with --show-stack-traces
```

Fix:
`npm i @openzeppelin/contracts-upgradeable`

Required Change:
add @openzeppelin/contracts-upgradeable to package.json

**Comment by St4rgarden** [comment]
Fixed
